# <center>  <font color='blue'> Unidad 4: Introducción a NumPy </font> </center>

<center>
<img src="https://user-images.githubusercontent.com/50221806/86498201-a8bd8680-bd39-11ea-9d08-66b610a8dc01.png" width="25%">
</center>

#### <center>  Sitio Web Oficial NumPy: [https://numpy.org/](https://numpy.org/) </center>

## <font color='red'> ¿Qué es NumPy? </font>
---

**NumPy** (abreviatura de "*Numerical Python*") es una biblioteca fundamental para la computación científica en *Python*.
    
**NumPy** es una biblioteca científica cálculos numéricos 
y operaciones con matrices y arreglos multidimensionales. Proporciona un conjunto de herramientas y funciones 
eficientes para trabajar con datos numéricos, lo que la hace muy útil en áreas como la ciencia de datos, 
la ingeniería, las matemáticas y la física, entre otros campos.

### Características principales

- **Creación de arrays:** Los arrays NumPy son la base para el manejo de datos numéricos en Python. 
Los arrays pueden ser unidimensionales (vectores), bidimensionales (matrices) o de dimensiones superiores.
- **Operaciones con arrays:** NumPy proporciona una amplia gama de operaciones para trabajar con arrays, incluyendo operaciones aritméticas, comparaciones, operaciones lógicas y mucho más.
- **Funciones matemáticas:** NumPy incluye una amplia gama de funciones matemáticas, como funciones trigonométricas, funciones estadísticas y funciones especiales.
- **Álgebra lineal:** NumPy proporciona potentes herramientas para el álgebra lineal, incluyendo operaciones con matrices, resolución de sistemas de ecuaciones, cálculo de autovalores y autovectores, y mucho más.
- **Generación de números aleatorios:** NumPy ofrece funciones para generar números aleatorios de diferentes distribuciones de probabilidad, como uniforme, normal, binomial y muchas más.
- **Visualización de datos:** NumPy puede ser utilizado para crear gráficos y diagramas para visualizar datos científicos.
- **Módulos adicionales:** NumPy cuenta con una serie de módulos adicionales que proporcionan herramientas específicas para diferentes áreas, como scipy para el análisis estadístico y matplotlib para la creación de gráficos.

### Aplicaciones:

**NumPy** se utiliza en una amplia variedad de aplicaciones, incluyendo:

- **Ciencia de datos**: NumPy es una herramienta esencial para el análisis de datos, el aprendizaje automático y la inteligencia artificial.
- **Ingeniería:** NumPy se utiliza en ingeniería para realizar simulaciones numéricas, resolver problemas de optimización y analizar datos experimentales.
- **Matemáticas:** NumPy se puede utilizar para resolver ecuaciones matemáticas, calcular integrales y derivadas, y visualizar gráficos.
- **Finanzas:** NumPy se utiliza en finanzas para modelar mercados financieros, analizar riesgos y desarrollar estrategias de inversión.
- **Ciencia:** NumPy se utiliza en ciencias como la física, la química, la biología y la astronomía para analizar datos, realizar simulaciones y desarrollar modelos.
    
### ¿Cómo importar NumPy?
    
Para importar **NumPy** en *Python*, simplemente utilizamos la siguiente sintaxis:

In [19]:
import numpy as np

- `np` es una convención ampliamente aceptada y utilizada en la comunidad de Python para referirse a **Numpy**.
- Una vez que hemos importado **NumPy** de esta manera, podemos acceder a todas sus funciones y módulos.

## <font color='purple'> 1. Creación de arrays (arreglos) en NumPy </font>

Los arrays en **NumPy** son la base para el manejo de datos numéricos en *Python*. 
Son estructuras de datos multidimensionales que almacenan elementos del mismo tipo. 
A diferencia de las listas de Python, que pueden almacenar elementos de diferentes tipos, 
los arrays **NumPy** solo pueden almacenar elementos del mismo tipo. Esto hace que los arrays **NumPy** sean mucho más eficientes 
para el almacenamiento y procesamiento de datos numéricos.

La siguiente tabla proporciona una comparación clara y concisa entre las listas de Python y los arreglos de NumPy, destacando sus diferencias y ejemplos de uso.



| Característica                  | Listas de Python                     | Arreglos de NumPy                         |
|---------------------------------|--------------------------------------|-------------------------------------------|
| **Tipos de Datos**              | Heterogéneas (diferentes tipos)      | Homogéneos (mismo tipo)                   |
| **Rendimiento**                 | Menos eficiente para operaciones     | Más rápido y eficiente en operaciones     |
|                                 | numéricas y matemáticas intensivas   | numéricas y matemáticas intensivas        |
| **Funcionalidad y Operaciones** | General y flexible                   | Optimizada para operaciones matemáticas   |
|                                 |                                      | y científicas                             |
| **Dimensionalidad**             | Principalmente unidimensionales,     | Naturalmente multidimensionales           |
|                                 | pueden anidar listas                 |                                           |
| **Indexación y Segmentación**   | Indexación estándar y segmentación   | Indexación avanzada, incluyendo booleana  |
|                                 | con slices                           | y segmentación multidimensional           |
| **Operaciones Básicas**         | No vectorizadas                      | Vectorizadas                              |
| **Multidimensionalidad**        | Estructuras anidadas para matrices   | Soporta matrices y tensores directamente  |
| **Funcionalidad Científica**    | Necesita bibliotecas adicionales     | Funciones científicas y matemáticas       |
|                                 |                                      | optimizadas integradas                    |
| **Ejemplo: Suma de Elementos**  | `[a + b for a, b in zip(lista_a, lista_b)]` | `arreglo_a + arreglo_b`                  |
| **Ejemplo: Operaciones**        | `[x * 2 for x in lista]`             | `arreglo * 2`                             |
| **Ejemplo: Multidimensionalidad** | `matriz[1][1]`                      | `matriz[1, 1]`                            |
| **Ejemplo: Funcionalidad Científica** | `import statistics` <br> `statistics.mean(datos)` | `np.mean(datos)`                   |



#### A partir de listas 
La forma más sencilla de crear un array NumPy es a partir de una lista de Python. 
La función `np.array()` convierte una lista en un array NumPy.

In [ ]:
# Crear un array a partir de una lista de enteros
lista_enteros = [1, 2, 3, 4, 5]
array_enteros = np.array(lista_enteros)

# Crear un array a partir de una lista de números reales
lista_reales = [1.2, 3.4, 5.6, 7.8, 9.0, 10.2]
array_reales = np.array(lista_reales)

print(array_enteros)
array_enteros

#### Con valores literales: 
También se pueden crear arrays NumPy directamente con valores literales.

In [ ]:
# Crear un array unidimensional de números enteros
array_enteros = np.array([1, 2, 3, 4, 5])

# Crear un array bidimensional de números reales
array_reales = np.array([1.2, 3.4, 5.6])

#### Con funciones de NumPy
NumPy proporciona diversas funciones para crear arrays con valores específicos, como `np.zeros()`, `np.ones()`, `np.linspace()`, `np.arange()`.

In [36]:
# Crear un array unidimensional de ceros
ceros = np.zeros(10)

# Crear un array unidimensional de unos
unos = np.ones(10)

# Crear un array unidimensional de números espaciados uniformemente
#np.linspace(inicio, fin, num_puntos)
array_espaciado = np.linspace(0, 10, 50) # 50 valores entre 0 y 10

# Crear un array de números enteros de 0 a 10 (inclusive)
# np.arange(inicio, fin, paso)
enteros_1 = np.arange(10) # Por defecto inicio = 0 y paso = 1
enteros_2 = np.arange(5,20,1)

In [37]:
print(enteros_1)
print(enteros_2)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### Con valores aleatorios
NumPy ofrece diversas funciones para generar arrays con números aleatorios de diferentes distribuciones de probabilidad.
Las distribuciones de probabilidad más comunes son:

##### La función `np.random.randint(low, high, size)` en NumPy se utiliza para generar números aleatorios enteros dentro de un intervalo especificado. 

In [ ]:
# Generar un número aleatorio entero entre 0 y 9 (inclusive)
aleatorio_1 = np.random.randint(10)

# Generar un array de 5 números aleatorios enteros entre 5 y 15 (inclusive)
aleatorio_2 = np.random.randint(5, 16, size=5)

##### La distribución uniforme genera números aleatorios distribuidos uniformemente dentro de un intervalo especificado. Se utiliza con la función `np.random.rand()`.

In [ ]:
# Generar un array unidimensional de 10 números aleatorios uniformes entre 0 y 1
array_uniforme = np.random.rand(10)

##### La distribución normal genera números aleatorios con una forma de campana, con una media y una desviación estándar especificadas. Se utiliza con la función `np.random.randn()`.

In [24]:
# Generar un array unidimensional de 10 números aleatorios con distribución normal, con media 0 y desviación estándar 1
array_normal = np.random.randn(10)

### <font color='purple'> Tipos de arrays </font>

**Arrays unidimensionales (vectores)**: Los arrays unidimensionales, también conocidos como vectores, son arrays que solo tienen una dimensión. 
Se representan como una fila de elementos entre corchetes.

In [ ]:
# Crear un array unidimensional de números enteros
vector_1 = np.array([1, 2, 3, 4, 5])

**Arrays de dimensiones superiores:** Los arrays de dimensiones superiores son arrays que tienen tres o más dimensiones. Se representan como una serie de corchetes anidados, 
con el número de corchetes igual al número de dimensiones del array.

In [ ]:
# Crear un array bidimensional de números reales
array_reales = np.array([[1.2, 3.4, 5.6], [7.8, 9.0, 10.2]])

# Crear una matriz de ceros
M_ceros = np.zeros((2, 2)) # Matriz 2x2 de ceros

# Crear una matriz de unos
M_ones = np.ones((2, 2)) # Matriz 2x2 de unos

# Crear un arreglo con valores aleatorios
e = np.random.rand(3, 3)


### <font color='purple'> Propiedades de los arrays </font>

#### Tipo de dato: 
Todos los elementos de un array NumPy deben ser del mismo tipo de dato. 
El tipo de dato del array se puede obtener con la propiedad `dtype`.

In [41]:
# Obtener el tipo de dato del array

print(array_enteros.dtype)
print(array_reales.dtype)

int64
float64


#### Dimensión (`ndim`):

La dimensión de un array indica el número total de dimensiones que tiene. Se puede obtener la dimensión 
del array utilizando la propiedad `ndim`.

In [49]:
print(array_reales.ndim)

2


#### Forma: 
La forma de un array NumPy indica el número de dimensiones del array y el número de elementos en cada dimensión. 
La forma del array se puede obtener con la propiedad `shape`.

In [42]:
# Obtener la forma del array
print(array_reales.shape)


(2, 3)


#### Tamaño: 
El tamaño de un array NumPy indica el número total de elementos en el array. 
El tamaño del array se puede obtener con la función `len()` o con la propiedad `size`.

In [43]:
# Obtener el tamaño del array
print(len(array_enteros))

# Obtener el tamaño del array (alternativo)
print(array_enteros.size)


10
10


## <font color='purple'> 2. Operaciones básicas con arrays en NumPy </font>

**NumPy** proporciona una gran variedad de operaciones matemáticas y lógicas que se pueden aplicar 
directamente a arrays enteros. Estas operaciones permiten realizar cálculos eficientes y complejos sobre conjuntos de datos numéricos.

- **Suma:** array1 + array2
- **Resta:** array1 - array2
- **Multiplicación:** array1 * array2
- **División:** array1 / array2
- **Módulo:** array1 % array2
- **Potenciación:** array1 ** array2
- **Raíz cuadrada:** np.sqrt(array)
- **Logaritmo natural:** np.log(array)
- **Logaritmo en base 10:** np.log10(array)
- **Exponencial:** np.exp(array)
- **Funciones trigonométricas:** np.sin(array), np.cos(array), np.tan(array), 

In [51]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 4])
# a y b deben tener el mismo tamaño
# Suma
suma = np.add(a, b)

# Resta
resta = np.subtract(a, b)

# Multiplicación
multiplicacion = np.multiply(a, b)

# División
division = np.divide(a, b)

print("Suma:", suma)
print("Suma:", a+b)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)


Suma: [5 7 7]
Suma: [5 7 7]
Resta: [-3 -3 -1]
Multiplicación: [ 4 10 12]
División: [0.25 0.4  0.75]


In [47]:
array_enteros = np.array([1, 2, 3, 4, 5])

# Suma de un escalar a todos los elementos del array
nuevo_array = array_enteros + 10

# Multiplicación de un escalar por todos los elementos del array
array_cuadrado = array_enteros ** 2

# Comparación con un escalar
array_logico = array_enteros > 3
print(array_logico)

[False False False  True  True]


## <font color='purple'> 3. Operaciones con vectores </font>

**NumPy**, a pesar de no estar diseñado específicamente para el manejo de vectores, permite realizar cálculos y 
operaciones con `arrays` que representan vectores en 2D y 3D. 

In [10]:
import numpy as np

# Definamos los vectores

# Vector 2D representado como un array
vector_2D = np.array([3, 4])

# Vector 3D representado como un array
vector_3D = np.array([1, 2, 3])

#### Magnitud: 
La magnitud de un vector, también conocida como norma euclidiana, representa la longitud del vector en el espacio. 
Se puede calcular utilizando la función `np.linalg.norm()`.

In [11]:
# Imprimir la magnitud
print(f"Magnitud vector_2D: {np.linalg.norm(vector_2D)}")
print(f"Magnitud vector_3D: {np.linalg.norm(vector_3D)}")

Magnitud vector_2D: 5.0
Magnitud vector_3D: 3.7416573867739413


#### Dirección:

La dirección de un vector 2D se define como el ángulo que forma con una referencia, como el eje x positivo. 
Se puede calcular utilizando la función `np.arctan2()`.

La dirección de un vector 3D se define por dos ángulos: el ángulo acimutal ($\phi$) y el ángulo polar (de elevación) ($\theta$). 
Se pueden calcular utilizando las funciones `np.arctan2()` y `np.arccos()`, respectivamente.


In [14]:
# Cálculo del ángulo en radianes
angulo_radianes = np.arctan2(vector_2D[1], vector_2D[0])

# Conversión a grados
angulo_grados = np.degrees(angulo_radianes)

# Imprimir el ángulo en grados
print("Dirección (grados):", angulo_grados)


Dirección (grados): 53.13010235415598


In [16]:
# Cálculo del ángulo acimutal (en radianes)
phi = np.arctan2(vector_3D[1], vector_3D[0])

# Cálculo del ángulo de elevación (en radianes)
theta = np.arccos(vector_3D[2] / np.linalg.norm(vector_3D))

# Conversión a grados
phi_grados = np.degrees(phi)
theta_grados = np.degrees(theta)

# Imprimir los ángulos en grados
print("Ángulo acimutal (grados):", phi_grados)
print("Ángulo de elevación (grados):", theta_grados)


Ángulo acimutal (grados): 63.43494882292201
Ángulo de elevación (grados): 36.69922520048988


#### Normalización (vector unitario):

La normalización de un vector 3D consiste en escalarlo para que su magnitud sea igual a 1. Se realiza dividiendo 
el vector por su magnitud.

In [19]:
# Normalización del vector (Vector unitario)
vector_unitario = vector_3D / np.linalg.norm(vector_3D)

# Imprimir el vector normalizado
print("Vector unitario:", vector_unitario)
print(np.linalg.norm(vector_unitario))

Vector unitario: [0.26726124 0.53452248 0.80178373]
1.0


#### Distancia entre dos puntos:

La distancia entre dos puntos en el espacio 3D se calcula utilizando la función `np.linalg.norm()`.

In [24]:
import numpy as np

# Punto 1 representado como un array
punto1_3d = np.array([1, 2, 3])

# Punto 2 representado como un array
punto2_3d = np.array([4, 5, 6])

print(np.linalg.norm(punto2_3d - punto1_3d))

5.196152422706632


#### Producto escalar y vectorial:

El producto escalar y vectorial se calculas utilizando la funciones `np.dot()` and `np.cross()`, respectivamente.

In [22]:
# Vector 3D 1 representado como un array
vector_1 = np.array([1, 2, 3])

# Vector 3D 2 representado como un array
vector_2 = np.array([4, 5, 6])

# Imprimir el producto escalar y vectorial
print(f'Producto escalar: {np.dot(vector_1, vector_2)}')
print(f'Producto vectorial: {np.cross(vector_1, vector_2)}')

Producto escalar: 32
Producto vectorial: [-3  6 -3]


## <font color='purple'>  4. Algebra lineal </font>

In [24]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Multiplicación de matrices
multiplicacion_matrices = np.dot(A, B)

# Inversión de matriz
inversion = np.linalg.inv(A)

# Determinante
determinante = np.linalg.det(A)

# Cálculo de la traza
traza = np.trace(A)

print("Multiplicación de matrices:\n", multiplicacion_matrices)
print("Inversión de matriz:\n", inversion)
print("Determinante:", determinante)
print("Traza:", traza)
print("Transpuesta", np.transpose(B))

Multiplicación de matrices:
 [[19 22]
 [43 50]]
Inversión de matriz:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinante: -2.0000000000000004
Traza: 5
Transpuesta [[1 3]
 [2 4]]


### Sistemas de ecuaciones lineales (SEL)

La función `np.linalg.solve()` en NumPy se utiliza para resolver sistemas de ecuaciones lineales (SEL) representados por 
matrices. Es una herramienta fundamental para el álgebra lineal y tiene diversas aplicaciones en áreas como la física, 
la ingeniería, la optimización y el análisis de datos.

```python
# Sintaxis
np.linalg.solve(A, b)
```

**Explicación de los parámetros:**

**A:** Una matriz cuadrada que representa los coeficientes del sistema de ecuaciones lineales. La matriz debe ser de dimensiones 
$(n \times n)$, donde n es el número de variables y ecuaciones.
    
**b:** Un vector que representa los términos independientes del sistema de ecuaciones lineales. 
  El vector debe tener longitud $n$, igual al número de variables.

**Valor de retorno:**

La función `np.linalg.solve()` devuelve un vector que representa la solución del sistema de ecuaciones lineales.  
  La longitud del vector de salida es $n$, igual al número de variables.
  

##### Resolver un sistema de ecuaciones lineales 2x2

Consideremos el siguiente sistema de ecuaciones lineales:

\begin{eqnarray}
2x + y &=& 4 \\
3x - y &=& 5
\end{eqnarray}

In [33]:
# Matriz 2x2 de los coeficientes del sistema
A = np.array([[2, 1], [3, -1]])
# Vector de los términos independientes
b = np.array([4, 5])

# Solución del sistema de ecuaciones lineales.
x = np.linalg.solve(A, b)

# Imprimir solución:
print("Solución:", x)
print(f'Solución: x = {x[0]}, y = {x[1]}')

Solución: [1.8 0.4]
Solución: x = 1.8, y = 0.4000000000000002


##### Resolver un sistema de ecuaciones lineales 3x3

Consideremos el siguiente sistema de ecuaciones lineales:

\begin{eqnarray}
x + 2y + 3z &=& 6 \\
2x + y - z &=& -1 \\
x + y + z &=& 4
\end{eqnarray}

In [2]:
# Matriz 2x2 de los coeficientes del sistema
A = np.array([[1, 2, 3], [2, 1, -1], [1, 1, 1]])
# Vector de los términos independientes
b = np.array([6, -1, 4])

# Solución del sistema de ecuaciones lineales.
x = np.linalg.solve(A, b)

# Imprimir solución:
print("Solución:", x)


Solución: [  9. -12.   7.]


## <font color='purple'> 5. Funciones Estadísticas (Medidas estadísticas) </font>

NumPy ofrece un conjunto de funciones estadísticas para analizar y describir datos numéricos almacenados en arrays. 
Estas funciones abarcan una amplia gama de operaciones estadísticas comunes, desde medidas básicas de centralidad y 
dispersión hasta pruebas estadísticas más complejas.

**Medidas básicas:**

- `np.mean()`: Calcula la media aritmética de los elementos de un array.
- `np.median()`: Calcula la mediana de los elementos de un array.
- `np.mode()`: Calcula el modo (valor más frecuente) de los elementos de un array.

**Medidas de dispersión:**

- `np.var()`: Calcula la varianza de los elementos de un array.
- `np.std()`: Calcula la desviación estándar de los elementos de un array.
- `np.quantile()`: Calcula los cuartiles (percentiles 25, 50 y 75) de los elementos de un array.

**Funciones de distribución de probabilidad:**

- `np.random.rand()`: Genera números aleatorios uniformes entre 0 y 1.
- `np.random.randn()`: Genera números aleatorios con distribución normal estándar.
- `np.random.binomial()`: Genera números aleatorios con distribución binomial.
- `np.random.poisson()`: Genera números aleatorios con distribución de Poisson.

**Pruebas estadísticas:**

- `np.t_test()`: Realiza una prueba t de Student para comparar dos muestras independientes.
- `np.anova()`: Realiza un análisis de varianza (ANOVA) para comparar dos o más muestras.
- `np.chi2_test()`: Realiza una prueba de chi-cuadrado para evaluar la independencia de dos variables categóricas.
- `np.corrcoef()`: Calcula el coeficiente de correlación de Pearson entre dos variables.


In [ ]:
import numpy as np

datos = np.array([10, 25, 32, 41, 28])

# Media
media = np.mean(datos)

# Mediana
mediana = np.median(datos)

# Desviación estándar
desviacion_estandar = np.std(datos)

# Varianza
varianza = np.var(datos)

print("Media:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion_estandar)
print("Varianza:", varianza)


## <font color='purple'> 6. Indexación y segmentación </font>

NumPy proporciona potentes herramientas para indexar y segmentar arrays de manera eficiente. 
Estas operaciones permiten acceder a elementos específicos dentro de un array o extraer subconjuntos de datos 
para su análisis o procesamiento.

#### Indexación Básica:

**Indexación única:** Se utiliza para acceder a un elemento específico dentro de un array utilizando su índice. 
La indexación comienza en 0.

In [ ]:
# Array de ejemplo
array_ejemplo = np.array([10, 20, 30, 40, 50])

# Acceso al primer elemento (índice 0)
elemento1 = array_ejemplo[0]

# Acceso al último elemento (índice -1)
ultimo_elemento = array_ejemplo[-1]

print("Primer elemento:", elemento1)
print("Último elemento:", ultimo_elemento)


#### Indexación múltiple

Permite acceder a elementos específicos dentro de un array multidimensional
utilizando sus índices correspondientes en cada dimensión

In [9]:
# Array bidimensional de ejemplo
array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceso al elemento en la fila 1, columna 2
elemento = array_2D[0, 0]

print("Elemento específico:", elemento)


Elemento específico: 1


#### Segmentación:

Segmentación de rangos permite extraer subconjuntos de datos de un array especificando un rango de índices.

In [13]:
# Array de ejemplo
array_ejemplo = np.array([10, 20, 30, 40, 50])

# Segmentación de los primeros tres elementos
subconjunto1 = array_ejemplo[:3]

# Segmentación de los últimos dos elementos
subconjunto2 = array_ejemplo[-2:]

print("Subconjunto 1:", subconjunto1)
print("Subconjunto 2:", subconjunto2)


Subconjunto 1: [10 20 30]
Subconjunto 2: [40 50]


####  Indexación booleana:

Indexación con arrays booleanos permite seleccionar elementos de un array en base a una condición booleana.

In [18]:
# Array de ejemplo
array_ejemplo = np.array([10, 20, 30, 40, 50])

# Array booleano con condición
condicion = array_ejemplo > 30

# Segmentación utilizando la condición booleana
subconjunto_condicion = array_ejemplo[condicion]

print(condicion)
print("Subconjunto con condición:", subconjunto_condicion)

[False False False  True  True]
Subconjunto con condición: [40 50]


array([False, False, False,  True,  True])

In [19]:
import numpy as np

# Arreglo de ejemplo
a = np.arange(1, 13)

# Cambiar la forma del arreglo
reshaped = a.reshape((3, 4))

# Transponer el arreglo
transposed = reshaped.T

print("Arreglo original:", a)
print("Arreglo reshaped:\n", reshaped)
print("Arreglo transpuesto:\n", transposed)


Arreglo original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Arreglo reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Arreglo transpuesto:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
